class ReportGenerator:

    def generate(
        self,
        validation_report,
        ats_report,
        output_path
    ):

        with open(output_path, "w", encoding="utf-8") as file:

            file.write("ATS RESUME AI AGENT REPORT\n")
            file.write("=" * 60 + "\n\n")

            file.write("RESUME VALIDATION\n")
            file.write("-" * 30 + "\n")

            for section, status in validation_report.items():

                if section == "Overall Status":
                    continue

                symbol = "✓" if status else "✗"

                file.write(f"{section}: {symbol}\n")

            file.write("\nOverall Status: ")

            if validation_report["Overall Status"]:
                file.write("Valid\n")
            else:
                file.write("Incomplete\n")

            file.write("\n")
            file.write("=" * 60 + "\n\n")

            file.write(f"ATS SCORE : {ats_report['score']}%\n\n")

            file.write("MATCHED SKILLS\n")
            file.write("-" * 30 + "\n")

            for skill in ats_report["matched"]:
                file.write(f"✓ {skill}\n")

            file.write("\n")

            file.write("MISSING SKILLS\n")
            file.write("-" * 30 + "\n")

            for skill in ats_report["missing"]:
                file.write(f"✗ {skill}\n")

            file.write("\n")

            file.write("ADDITIONAL SKILLS\n")
            file.write("-" * 30 + "\n")

            for skill in ats_report["extra"]:
                file.write(f"• {skill}\n")

            file.write("\n")
            file.write("=" * 60 + "\n")
            file.write("Generated by ATS Resume AI Agent\n")