import os

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate


class ReportGenerator:

    def generate(
        self,
        validation_report,
        ats_report,
        output_path
    ):

        # ======================================================
        # GENERATE TXT REPORT
        # ======================================================

        with open(output_path, "w", encoding="utf-8") as file:

            file.write("ATS RESUME AI AGENT REPORT\n")
            file.write("=" * 60 + "\n\n")

            file.write("RESUME VALIDATION\n")
            file.write("-" * 30 + "\n")

            for section, status in validation_report.items():

                if section == "Overall Status":
                    continue

                symbol = "✓" if status else "✗"

                file.write(f"{section}: {symbol}\n")

            file.write("\nOverall Status: ")

            if validation_report["Overall Status"]:
                file.write("Valid\n")
            else:
                file.write("Incomplete\n")

            file.write("\n")
            file.write("=" * 60 + "\n\n")

            file.write(f"ATS SCORE : {ats_report['score']}%\n\n")

            file.write("MATCHED SKILLS\n")
            file.write("-" * 30 + "\n")

            for skill in ats_report["matched"]:
                file.write(f"✓ {skill}\n")

            file.write("\n")

            file.write("MISSING SKILLS\n")
            file.write("-" * 30 + "\n")

            for skill in ats_report["missing"]:
                file.write(f"✗ {skill}\n")

            file.write("\n")

            file.write("ADDITIONAL SKILLS\n")
            file.write("-" * 30 + "\n")

            for skill in ats_report["extra"]:
                file.write(f"• {skill}\n")

            file.write("\n")
            file.write("=" * 60 + "\n")
            file.write("Generated by ATS Resume AI Agent\n")

        # ======================================================
        # GENERATE PDF REPORT
        # ======================================================

        pdf_path = os.path.splitext(output_path)[0] + ".pdf"

        doc = SimpleDocTemplate(pdf_path)

        styles = getSampleStyleSheet()

        story = []

        story.append(Paragraph("<b>ATS Resume AI Agent Report</b>", styles["Title"]))

        story.append(Paragraph("<br/><b>Resume Validation</b>", styles["Heading2"]))

        for section, status in validation_report.items():

            if section == "Overall Status":
                continue

            symbol = "✓" if status else "✗"

            story.append(
                Paragraph(f"{symbol} {section}", styles["Normal"])
            )

        story.append(Paragraph("<br/>", styles["Normal"]))

        overall = (
            "Valid"
            if validation_report["Overall Status"]
            else "Incomplete"
        )

        story.append(
            Paragraph(
                f"<b>Overall Status:</b> {overall}",
                styles["Normal"]
            )
        )

        story.append(
            Paragraph(
                f"<b>ATS Score:</b> {ats_report['score']}%",
                styles["Heading2"]
            )
        )

        story.append(
            Paragraph("<b>Matched Skills</b>", styles["Heading2"])
        )

        for skill in ats_report["matched"]:
            story.append(
                Paragraph(f"• {skill}", styles["Normal"])
            )

        story.append(
            Paragraph("<b>Missing Skills</b>", styles["Heading2"])
        )

        for skill in ats_report["missing"]:
            story.append(
                Paragraph(f"• {skill}", styles["Normal"])
            )

        story.append(
            Paragraph("<b>Additional Skills</b>", styles["Heading2"])
        )

        for skill in ats_report["extra"]:
            story.append(
                Paragraph(f"• {skill}", styles["Normal"])
            )

        story.append(Paragraph("<br/>", styles["Normal"]))

        story.append(
            Paragraph(
                "<i>Generated by ATS Resume AI Agent</i>",
                styles["Normal"]
            )
        )

        doc.build(story)